name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: sudo ./build-swtpm.sh
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swtpm-artifacts
          path: |
            /tmp/swtpm-packages.tgz
